docs(samples): add iam deny samples and test
googleapis/java-iam pull request #371
Opened 2022-06-30 05:18 UTC by Sita04

Added samples and tests for IAM Deny launch.

2022-07-06 15:19 UTC, kurtisvg approved these changes
Great job.

2022-07-06 23:36 UTC, hegemonic requested changes
Looks good overall! Most of these comments are very minor.

2022-07-06 23:36 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/UpdateDenyPolicy.java
> +      // The attachment point is identified by its URL-encoded full resource name. Hence, replace
delete "full"

2022-07-06 23:36 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/UpdateDenyPolicy.java
> +              // https://cloud.google.com/iam/docs/principal-identifiers#v2
change to: https://cloud.google.com/iam/help/deny/principal-identifiers

2022-07-06 23:36 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/UpdateDenyPolicy.java
> +              // Example, if you want to deny certain permissions to a group but exempt few
s/few/a few/

2022-07-06 23:36 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/UpdateDenyPolicy.java
> +              // https://cloud.google.com/iam/docs/deny-permissions-support
change to: https://cloud.google.com/iam/help/deny/supported-permissions

2022-07-06 23:36 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/UpdateDenyPolicy.java
> +      // Set the policy resource path, version (etag) and the updated policy rules.
s/policy rules/deny rules/

2022-07-07 16:11 UTC, Sita04 commented on samples/cloud-client/snippets/src/main/java/CreateDenyPolicy.java
> +              .replaceAll("/", "%2F");
Modified it to use URLEncoder. Initially, thought of making the change obvious by just replacing the chars.

2022-07-07 16:11 UTC, Sita04 commented
@hegemonic PTAL.

2022-07-07 17:05 UTC, hegemonic commented on samples/cloud-client/snippets/src/main/java/CreateDenyPolicy.java
> +              .replaceAll("/", "%2F");
Thanks! I understand your thinking, but I think this way is probably a little safer.

2022-07-07 17:05 UTC, hegemonic approved these changes
Looks great, Sita—thank you!

2022-07-08 06:59 UTC, merged